// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyabF3FlRIRkhbAGfXHEZLNpTAuL72yeI',
    appId: '1:1066108335336:web:ea1d6b081a370f26c2455d',
    messagingSenderId: '1066108335336',
    projectId: 'taskapp-f3894',
    authDomain: 'taskapp-f3894.firebaseapp.com',
    storageBucket: 'taskapp-f3894.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG9V5rlu7r7ILuKeo0o7T9LrAfYiElQfE',
    appId: '1:1066108335336:android:6a31d549901c54bbc2455d',
    messagingSenderId: '1066108335336',
    projectId: 'taskapp-f3894',
    storageBucket: 'taskapp-f3894.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9fWogoZfwj5R_Zxu-C0-Xnuw8Iq7rSsk',
    appId: '1:1066108335336:ios:9da73fe42a7b411dc2455d',
    messagingSenderId: '1066108335336',
    projectId: 'taskapp-f3894',
    storageBucket: 'taskapp-f3894.firebasestorage.app',
    iosBundleId: 'com.example.newTaskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9fWogoZfwj5R_Zxu-C0-Xnuw8Iq7rSsk',
    appId: '1:1066108335336:ios:9da73fe42a7b411dc2455d',
    messagingSenderId: '1066108335336',
    projectId: 'taskapp-f3894',
    storageBucket: 'taskapp-f3894.firebasestorage.app',
    iosBundleId: 'com.example.newTaskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoU_vJi1RuKok2Xj6ghaO-B9Q97SBnC3I',
    appId: '1:1066108335336:web:8afd02d50452de08c2455d',
    messagingSenderId: '1066108335336',
    projectId: 'taskapp-f3894',
    authDomain: 'taskapp-f3894.firebaseapp.com',
    storageBucket: 'taskapp-f3894.firebasestorage.app',
  );
}
